Added setmode binary for stdout on windows
vapier/ncompress pull request #31
Opened 2021-01-26 21:06 UTC by andrew-aladev

Closes #30

2021-01-26 23:01 UTC, vapier requested changes

2021-01-26 23:19 UTC, andrew-aladev commented on compress42.c
> +				setmode(fdin, O_BINARY);
Thank you, I've updated it.

2021-01-26 23:21 UTC, andrew-aladev commented
I've used msvc with the following command `cl /O2 -o compress-windows-x64.exe -DNOFUNCDEF -DUSERMEM=800000 -DREGISTERS=3 compress42.c`. Now it works perfect like on linux and mac.

2021-01-26 23:37 UTC, vapier commented
ah i just noticed this is against the ncompress-4.2.4 branch.  i'm not planning on making anymore releases from that.  can you redo the change against the main branch and i can look at creating the first 5.x release ?  there's more Windows fixes in the main branch that haven't been included in the ncompress-4.2.4 branch.

2021-01-27 08:26 UTC, andrew-aladev commented
Ok, I will update pr today evening, thanks.

2021-01-28 00:11 UTC, closed without merging